### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by coryhouse** [ckrupani/React-Redux-App#1]
You need to change this: https://github.com/ckrupani/React-Redux-App/blob/master/webpack.config.dev.js#L28

That line should be:

```
        { test: /\.js$/, include: path.join(__dirname, 'src'), loaders: ['babel']},
```

Why did you add the query? That's not suggested in the course.

**Comment by ckrupani** [comment]
Hi,
I was trying solutions available online for this problem. I added query key at that time. Event without query it is giving the same error.

I found the bug after comparing your line with mine.
Mine code:  
`{ test: /\.js$/, include: path.join(__dirname + 'src'), loaders: ['babel'] },`
Your code:
`{ test: /\.js$/, include: path.join(__dirname, 'src'), loaders: ['babel']},`

I am using '+' in path.join which is wrong.

Thank you very much for your support.
